spring:
  application:
    name: tech-test-java

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tech_test
    username: ${DB_USER}
    password: ${DB_PWD}

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    drop-first: false
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
    clear-checksums: false
    test-rollback-on-update: false
    change-log: classpath:db/changelog/changelog-master.xml
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    liquibase-schema: ${spring.jpa.properties.hibernate.default_schema}