logging:
  level:
    root: info

server:
  port: 9090

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

persistence:
  use-jpa: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:postgresql://localhost:5432/tech_test
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      #hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect

  flyway:
    baseline-on-migrate: true