CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMERID INT PRIMARY KEY NOT NULL,
    CUSTOMER_NAME VARCHAR(50),
    COUNTRY VARCHAR(50),
    DATE_OF_BIRTH DATE
    );


CREATE TABLE IF NOT EXISTS ORDERS (
    oderId int primary key not null,
    amount number(10,2),
    vat number (3,1)
    --foreign key (CUSTOMERID) references CUSTOMER(CUSTOMERID)
);

--INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (1,'Xolisani','South Africa', '2002-11-15');
INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (1,'Xolisani','SA', '2002-11-15');
INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (2,'Christopher','UK', '2003-12-31');
INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (3,'Xerxes','UK', '2004-01-12');
INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (4,'Judith','SA', '2005-05-01');
INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (5,'Ashal','UK', '1999-02-14');
INSERT INTO CUSTOMER (CUSTOMERID, CUSTOMER_NAME, COUNTRY, DATE_OF_BIRTH) VALUES (6,'Linda','SA', '2000-08-30');
commit ;

-- --AUTO_INCREMENT